### ISSUE TITLE
Compatibility with IntelliJ Ultimate 2016

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [intellij-rust/intellij-rust.github.io#10]
Recently I have updated my IntelliJ installation to the 2016 version (now moved to yearly release numbering) and I can't get my projects previously configured with the rust SDK and the plugin to work, and I can't find a way to add a rust SDK to it (the existing ones are marked as invalid).

Any ideas on workarounds to get this to work?

IntelliJ version: 
IntelliJ IDEA 2016.2
Build #IU-162.1121.32, built on July 9, 2016
Licensed to Andrew Mackenzie
Subscription is active until June 19, 2017
For educational use only.
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Rust plugin:
Version: 0.0.1.808

**Comment by jajakobyly** [comment]
Hi!

Unfortunately this issue has been posted to our website's repo. Could you resubmit it in plugin's repository? :smile: 

As for SDK, you can change it in `Settings > Languages & Frameworks > Rust` window:
![idea_2016-07-16_20-09-15](https://cloud.githubusercontent.com/assets/3450050/16896349/3a1642e4-4b91-11e6-91a4-c4a3b8330f6c.png)
(screen is from non-Rust project)
