### ISSUE TITLE
Mention ra’s proc-macro-server in FAQ

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust.github.io#126]
https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#use-rls-racer-rustanalyzer

I wonder if it makes to say “we share some infrastructure code for running procedural macros with rust-analyzer”.

https://github.com/intellij-rust/intellij-rust/blob/d5404e78249ec7f30a50ea93a506973383fe7d82/native-helper/Cargo.toml#L7

**Comment by MarinaKalashina** [comment]
Thanks for pointing this out! Done - https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#use-rls-racer-rustanalyzer

**Comment by matklad** [comment]
Perfect, thanks @MarinaKalashina !
