### ISSUE TITLE
Changelog 171: 404

### ISSUE THREAD

**Issue by develop7** [intellij-rust/intellij-rust.github.io#153]
https://intellij-rust.github.io/2022/05/30/changelog-171.html is 404 & https://intellij-rust.github.io/thisweek/ doesn't mention changelog \#171

**Comment by ozkriff** [comment]
https://github.com/intellij-rust/intellij-rust.github.io/actions/runs/2408464354 is still running

**Comment by develop7** [comment]
@ozkriff ya, and just got started after 14 minutes in "waiting for a runner to pick the job up"

**Comment by Undin** [comment]
Works now

**Comment by develop7** [comment]
it's up
