### ISSUE TITLE
GFY for Expand module refactoring

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust.github.io#21]
It is now a real refactoring thanks to intellij-rust/intellij-rust@6487a51, so making "readable" GFY should be possible now

**Comment by matklad** [comment]
https://github.com/intellij-rust/intellij-rust/issues/587

**Comment by Undin** [comment]
Since we moved all plugin documentation to [Marketplace](https://plugins.jetbrains.com/plugin/8182-rust/docs) and don't show features page on intellij-rust.github.io anymore (only redirect to Marketplace), I think this issue can be closed as obsolete.
