### ISSUE TITLE
Get rid of GFYs for surrounders and live templates

### ISSUE THREAD

**Issue by mkaput** [intellij-rust/intellij-rust.github.io#24]
There are going to be a lot of them (23 live templates as for now). I think making gfy for each of them is senseless.

**Comment by matklad** [comment]
What about saying "we have live templates" ad provide a single moderately long GFY which show cases the most commonly used one? Also it might be nice to show how <kbd>Ctrl+J</kbd> <kbd>Ctrl+Alt+T</kbd> woks (presentation plugin)

**Comment by matklad** [comment]
`<Ctrl+J>` thing is rather important, because it lists available snippets.

**Comment by Undin** [comment]
Since we moved all plugin documentation to [Marketplace](https://plugins.jetbrains.com/plugin/8182-rust/docs) and don't show features page on intellij-rust.github.io anymore (only redirect to Marketplace), I think this issue can be closed as obsolete.
