### ISSUE TITLE
Features page: add ability to link to a particular feature

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust.github.io#25]

**Comment by matklad** [comment]
Pehaps adding `id` attributes to the necessary divs should be enough?

**Comment by matklad** [comment]
Ok, id's work, but if you actually follow that link, a part of the description would be hidden by the page header...

**Comment by jajakobyly** [comment]
Yes, there is special partial called `h` for it. Docs use it if you need reference

**Comment by jajakobyly** [comment]
Oh yeah I see what you wanted to do. In that particular situation, ids will probably be the best way to go. The issue of bad position cannot be fixed, only workarounded with some additional markup.

**Comment by Undin** [comment]
Our documentation is migrating to JetBrains [Marketplace](https://plugins.jetbrains.com/plugin/8182-rust/docs) so close this issue

**Comment by matklad** [comment]
Oh wow, I've been promised a marketplace page so many years ago, glad to see it finally come to frution!
