### ISSUE TITLE
It should be possible to link to the particular Quick Start section

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust.github.io#3]
Perhaps we should add a table of contents to it as well?

**Comment by jajakobyly** [comment]
Each header already has it's unique id based on it's contents, though they are not 
accompanying `<a>` tags, so getting these urls is not as easy as for instance on GitHub.

Unfortunately this, and also TOC stuff, will require some JavaScript shenanigans probably, as gh-pages are quite limited here.

**Comment by matklad** [comment]
https://github.com/dafi/jekyll-toc-generator

**Comment by jajakobyly** [comment]
Readme states that it doesn't work on gh pages

**Comment by jajakobyly** [comment]
I have an idea on this, will implement during weekend
