### ISSUE TITLE
Support for workspaces in Run/Debug configurations

### ISSUE THREAD

**Issue by stephanbuys** [intellij-rust/intellij-rust.github.io#34]
Hi, I'm using https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md

It would be awesome to be able to pick a "member" project for a cargo command (or even just change the cargo command working directory).

At the moment I'm working around the issue by just opening up my "members" in a different IDE window.

You can reference https://github.com/habitat-sh/habitat for a production example.

**Comment by matklad** [comment]
Yep, this is a known pain point. The best workaround currently would be to specify `--manifest-path` flag for each run configuration.

I intend to fix this in Cargo: currently if you run `cargo test --package foo` in the root of the workspace, you get the "virtual manifest error".

**Comment by matklad** [comment]
upstream issue: https://github.com/rust-lang/cargo/issues/3194

**Comment by matklad** [comment]
Moved to the plugin repo: https://github.com/intellij-rust/intellij-rust/issues/733
