### ISSUE TITLE
Supported IDE versions

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust.github.io#54]
https://intellij-rust.github.io/install.html says that rust plugin is compatible with 2016.1 builds and newer. It's not really true because latest plugin versions support only 2017.2 builds and newer.

I think we should update this page to be consistent with the latest plugin changes.

**Comment by matklad** [comment]
Closed in https://github.com/intellij-rust/intellij-rust.github.io/commit/0203ac7aee70628cc72760db147f1635277b5cd9, thanks!
