### ISSUE TITLE
Download button is wrong

### ISSUE THREAD

**Issue by matklad** [intellij-rust/intellij-rust.github.io#7]
Download button at the main page feels weird. Preferably, the user should never see the ugly `plugins.jetbrains.com`. 

What do you think about the following UI: the button says **Install**, and it is simply a link to a page which explains how to install alpha/nightly channel from within IDE?

**Comment by jajakobyly** [comment]
:+1:

But maybe instead of separate page, some (maybe animated) pop-over or iTunes-like sliding pane?

**Comment by matklad** [comment]
I first also thought about revealing this info via an animation, but it has a couple of drawbacks:

* harder to implement
* harder to get right for specific use cases like disabled JavaScript or accessibility
* a dedicated Installation page will have an URL, which you can share

**Comment by jajakobyly** [comment]
> harder to implement

Hmm (not tested)
```javascript
document.getElementById("download-stable")
    .addEventListener("click", function(e) {
        document.getElementById("download-pane").classList.toggle("visible");
    });
```
and then some CSS Transition magic :smile: HTML5 is awesome!

> harder to get right for specific use cases like disabled JavaScript or accessibility
> a dedicated Installation page will have an URL, which you can share

Hmm, what about mixing these two approaches? Download page's contents will be put inside a partial template. It will be rendered as an animated pane on the front page **and** as a separate page. Download button will point to that separate page. Two birds killed with one stone.

**Comment by matklad** [comment]
Yep, this is the best approach.
