### ISSUE TITLE
Optimize Imports sorts `mod` after `use`

### ISSUE THREAD

**Issue by trivigy** [intellij-rust/intellij-rust.github.io#80]
Technically this doesn't make any difference but syntactically it is much easier to read when `use` statements are positioned after the `mod`. Almost like saying "from this imported module, use these things in the current scope."

Not sure if this is some kind of generic clion configuration or the intellij-rust specific but could not figure out how to change that. Would greatly appreciate any kind of advice.

**Comment by trivigy** [comment]
wrong repo. closing.

**Comment by U007D** [comment]
@trivigy Did you reopen this elsewhere by chance?  I'm having the same issue.

**Comment by trivigy** [comment]
@U007D I don't remember sorry.

**Comment by trivigy** [comment]
After thinking about it for a few extra days I actually think I just gave up and kept going with it as is.
